[workspace]
members = [
    "src/ic-plugin-api",
    "src/example-plugin",
    "src/c-conformance",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

ic-plugin-api = { path = "src/ic-plugin-api", version = "0.1.0" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
